![6'1-三种数据格式对比.png](./img/6'1-三种数据格式对比.png)

![6'1-tensor对象.png](./img/6'1-tensor对象.png)

In [1]:
import tensorflow as tf

## 利用列表创建张量

In [13]:
a = tf.constant([[1, 2], [3, 4]])

In [14]:
# 获取 numpy
a.numpy()

array([[1, 2],
       [3, 4]])

In [15]:
# 查看类型
type(a)

tensorflow.python.framework.ops.EagerTensor

In [16]:
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## 利用数字创建

In [19]:
tf.constant(1.0)

<tf.Tensor: id=6, shape=(), dtype=float32, numpy=1.0>

In [20]:
tf.constant(1.)

<tf.Tensor: id=7, shape=(), dtype=float32, numpy=1.0>

In [21]:
tf.constant(1.0, dtype=tf.float64)

<tf.Tensor: id=8, shape=(), dtype=float64, numpy=1.0>

![6'1-张量的数据类型.png](./img/6'1-张量的数据类型.png)

## 利用Numpy创建

In [23]:
import numpy as np

In [24]:
tf.constant(np.array([1, 2]))

<tf.Tensor: id=9, shape=(2,), dtype=int32, numpy=array([1, 2])>

In [25]:
tf.constant(np.array([1.0, 2.0]))

<tf.Tensor: id=10, shape=(2,), dtype=float64, numpy=array([1., 2.])>

In [26]:
tf.constant(np.array([1.0, 2.0]), dtype=tf.float32)

<tf.Tensor: id=11, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

## 常用方法

![6'1-张量的常用方法.png](./img/6'1-张量的常用方法.png)

### 1. cast(x,dtype)
改变元素数据类型

![6'1-改变数据类型.png](./img/6'1-改变数据类型.png)

In [28]:
# numpy
a = tf.constant(np.array([1,2]))
b = tf.cast(a, dtype=tf.float32)
b.dtype

tf.float32

#### 注意：由 **高精度** 转 **低精度** 有可能会出现溢出错误，导致结果不正确

In [29]:
# 数字
a = tf.constant(123456789, dtype=tf.int32)
tf.cast(a, tf.int16)

<tf.Tensor: id=16, shape=(), dtype=int16, numpy=-13035>

In [30]:
# Bool
tf.constant(True)

<tf.Tensor: id=17, shape=(), dtype=bool, numpy=True>

In [31]:
tf.constant([True, False])

<tf.Tensor: id=18, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [33]:
a = tf.constant([-1, 0, 1, 2])
tf.cast(a, dtype=tf.bool)

<tf.Tensor: id=21, shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [34]:
# 字符串
tf.constant('hello')

<tf.Tensor: id=22, shape=(), dtype=string, numpy=b'hello'>

### 2. convert_to_tensor()

将 numpy, list, number, bool, string 转换成 tensor

In [38]:
na = np.arange(12).reshape(3,4)
ta = tf.convert_to_tensor(na)

In [40]:
type(na)

numpy.ndarray

In [41]:
type(ta)

tensorflow.python.framework.ops.EagerTensor

### 3. is_tensor()
判断是否为 tensor

In [43]:
tf.is_tensor(na)

False

In [44]:
tf.is_tensor(ta)

True

### 4. 创建张量的快捷方式
    1. tf.zeros(shape, dtype = tf.float32) 全零张量
    2. tf.ones(shape, dtype = tf.float32)  全一张量
    3. tf.fill(dims, value)  填充张量 dims是形状
    4. tf.range(start, limit, delta=1, dtype) 数字序列
    5. tf.random.normal(shape, mean, stddev, dtype) 正态分布
    6. tf.random.truncated_normal(shape, mean, stddev, dtype) 截断正态分布
    7. tf.random.uniform(shape, minval, maxval, dtype) 均匀分布
    8. tf.random.shuffle() 打乱函数

tf.ones()

In [57]:
tf.ones(shape=(3,2))

<tf.Tensor: id=69, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

tf.zeros()

In [51]:
tf.zeros([6]) # 用列表表示形状

<tf.Tensor: id=42, shape=(6,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0.], dtype=float32)>

tf.fill()

In [53]:
# fill 没有 dtype， 而是根据 value 的类型自动转换成对应的类型
tf.fill([2,3], 9)

<tf.Tensor: id=48, shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

tf.random.normal(shape, mean, stddev, dtype)

当 mean 和 stddev 省略时，默认为标准正态分布


In [55]:
# 2x2 的张量， 元素服从标准正态分布
tf.random.normal([2,2])

<tf.Tensor: id=60, shape=(2, 2), dtype=float32, numpy=
array([[ 0.21838744, -0.6049696 ],
       [ 1.156868  , -1.2288462 ]], dtype=float32)>

In [56]:
# 创建三维张量， 元素服从正态分布
tf.random.normal([3,3,3], mean=0.0, stddev=2.0)

<tf.Tensor: id=66, shape=(3, 3, 3), dtype=float32, numpy=
array([[[-1.6037022 , -4.9700336 , -2.455714  ],
        [ 1.219253  ,  2.2826805 , -3.0222223 ],
        [ 2.3387809 ,  0.3811886 , -0.29948527]],

       [[ 0.29630923, -1.011629  , -2.1910849 ],
        [ 1.6972569 , -1.9681587 ,  1.3245022 ],
        [-1.762823  , -0.83287644,  2.0976946 ]],

       [[-0.67508376,  2.2979105 , -0.5556659 ],
        [ 0.29281557, -1.8492675 , -2.6318038 ],
        [ 3.6236572 , -1.8505367 ,  1.2564051 ]]], dtype=float32)>

tf.random.truncated_normal()

![6'1-正态分布.png](./img/6'1-正态分布.png)

tf.random.set_seed() 

设置随机种子，让随机数一致

In [59]:
tf.random.set_seed(8)
tf.random.normal([2,2])

<tf.Tensor: id=76, shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401, -0.7452462],
       [ 0.6908678, -0.7635988]], dtype=float32)>

In [60]:
tf.random.set_seed(8)
tf.random.normal([2,2])

<tf.Tensor: id=82, shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401, -0.7452462],
       [ 0.6908678, -0.7635988]], dtype=float32)>

tf.random.uniform()

In [61]:
tf.random.uniform(shape=(3, 3), minval=0, maxval=10, dtype='int32')

<tf.Tensor: id=86, shape=(3, 3), dtype=int32, numpy=
array([[6, 8, 3],
       [9, 5, 1],
       [8, 6, 1]])>

tf.random.shuffle()

总是打乱最外层

In [62]:
x = tf.constant([[1,2],[3,4],[5,6]])
tf.random.shuffle(x)

<tf.Tensor: id=88, shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]])>

In [63]:
y = [1,2,3,4,5]
tf.random.shuffle(y)

<tf.Tensor: id=90, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 5])>

In [75]:
x = tf.constant(np.arange(12),shape=(3,4,1))
tf.random.shuffle(x)

<tf.Tensor: id=98, shape=(3, 4, 1), dtype=int32, numpy=
array([[[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[ 0],
        [ 1],
        [ 2],
        [ 3]]])>

tf.range(start, limit, delta=1, dtype)

In [76]:
tf.range(10)

<tf.Tensor: id=102, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [77]:
tf.range(10,delta=2)

<tf.Tensor: id=106, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [78]:
tf.range(1,10,delta=2)

<tf.Tensor: id=110, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

## Torsor对象的属性 -- ndim、shape、dtype

In [79]:
a = tf.constant([[1,2],[3,4]])
print('ndim:',a.ndim)
print('dtype:',a.dtype)
print('shape:',a.shape)

ndim: 2
dtype: <dtype: 'int32'>
shape: (2, 2)


## Torsor对象的其他方法 -- shape()、size()、rank()

In [80]:
tf.shape(a)

<tf.Tensor: id=112, shape=(2,), dtype=int32, numpy=array([2, 2])>

In [81]:
tf.size(a)

<tf.Tensor: id=113, shape=(), dtype=int32, numpy=4>

In [83]:
# 维度
tf.rank(a)

<tf.Tensor: id=115, shape=(), dtype=int32, numpy=2>

## 张量与Numpy数组的关系

- 在 TensorFlow 种， <font color='green'>所有运算都是在张量之间进行的</font>
- Numpy 数组仅仅是作为输入和输出来使用
- 张量可以在CPU、GPU 和 TPU中运行
- Numpy只能在CPU中运行