# 维度变换

tf.reshape(tensor,shape)

In [3]:
import tensorflow as tf
import numpy as np

In [8]:
# tensor
a = tf.range(24)
b = tf.reshape(a,[2,3,4])
b

<tf.Tensor: id=15, shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [7]:
# numpy
tf.constant(np.arange(24).reshape(2,3,4))

<tf.Tensor: id=9, shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [6]:
tf.reshape(b,[4,-1])

<tf.Tensor: id=8, shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

## 多维度张量的轴 Axis
建议：用 shape 去理解 axis

![6'2-张量的轴.png](./img/6'2-张量的轴.png)

## 增加和删除维度

- 维度操作
    - [增加](#expand_dim)
    - [删除](#squeeze)
    - [变换](#transpose)
- 张量操作
    - [拼接](#concat)
    - [分割](#split)
    - [堆叠](#stack)
    - [分解](#unstack)

**拼接与堆叠的区别:** 拼接不会增加维度,只是在现有维度上把两个或者多个tensor或list进行拼接；而堆叠会增加一个维度。

#### <font id='expand_dim'>1. 增加维度</font>
tf.expand_dims(input, axis)

*二维例子*

In [46]:
t = tf.constant([1, 2])
print(t.shape)

(2,)


In [44]:
# axis=1 上加一个维度
# 之前shape = (2,)
# 之后shape = (2,1)  '1' 就是加的维度
t1 = tf.expand_dims(t,1)
print('t1"s shape:',t1.shape)
print(t1)

t1"s shape: (2, 1)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)


In [45]:
# axis=0 上加一个维度
# 之前shape = (2,)
# 之后shape = (1,2)  '1' 就是加的维度
t2 = tf.expand_dims(t,0)
print(t2.shape)

(1, 2)


In [47]:
t2

<tf.Tensor: id=60, shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

<tf.Tensor: id=46, shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]])>

In [48]:
# axis=-1 上加一个维度
# 之前shape = (2,)
# 之后shape = (2,1)  '1' 就是加的维度
t3 = tf.expand_dims(t,0)
print(t3.shape)

(1, 2)


In [49]:
t3

<tf.Tensor: id=63, shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

*三维例子*

In [51]:
a = tf.range(24)
b = tf.reshape(a,[2,3,4])
print(b.shape)

(2, 3, 4)


In [54]:
# (2, 3, 4) -> (1 ,2, 3, 4)
b1 = tf.expand_dims(b,0)
# (2, 3, 4) -> (2, 1, 3, 4)
b2 = tf.expand_dims(b,1)
# (2, 3, 4) -> (2, 3, 1, 4)
b3 = tf.expand_dims(b,2)
# (2, 3, 4) -> (2, 3, 4，1)
b4 = tf.expand_dims(b,3)
print(b1.shape)
print(b2.shape)
print(b3.shape)
print(b4.shape)

(1, 2, 3, 4)
(2, 1, 3, 4)
(2, 3, 1, 4)
(2, 3, 4, 1)


#### <font id='squeeze'>2. 删除维度</font>
删除axis指定的轴，axis可以是 **list** or **number** , 只能删除长度为1的维度

tf.squeeze(input, axis) 

如果不指定axis，自动删除所有长度为1的轴

In [60]:
ts = tf.constant(tf.range(24),shape=[2,3,4])
print('ts"s shape:',ts.shape)

ts"s shape: (2, 3, 4)


In [64]:
tss = tf.reshape(ts, [1,2,1,3,4])
print('tss"s shape:',tss.shape)

tss"s shape: (1, 2, 1, 3, 4)


In [66]:
# 不指定 axis，自动删除所有的axis=1
tf.shape(tf.squeeze(tss))

<tf.Tensor: id=126, shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [68]:
# 指定 axis
tf.shape(tf.squeeze(tss,[2]))

<tf.Tensor: id=128, shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

**注意：** 增加维度和删除维度，值改变了张量的视图，不改变张量的存储

#### <font id='transpose'>3. 维度变换</font>
tf.transpose(a, perm)

perm 是轴的循序

In [76]:
x = tf.constant(tf.range(24),shape=[2,3,4])
x

<tf.Tensor: id=144, shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [78]:
# 由 (2, 3, 4) -> (4, 3, 2)
tf.transpose(x)

<tf.Tensor: id=148, shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])>

In [81]:
# 使用perm， 控制要交换的轴
# 0 对应shape中的 4
# 1 对应shape中的 3
# 2 对应shape中的 2

# 转换后 (4,3,2) -> (3,2,4)
tf.transpose(x, perm=[1,0,2])

<tf.Tensor: id=153, shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])>

#### <font id='concat'>4. 拼接张量</font>
tf.concat( tensor, axis )

axis 按照哪一个维度进行拼接， 相当于合并这个维度

In [96]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]

上面两组tensor的shape都是相等的 (2, 3)

In [97]:
# 将axis=0的维度拼接
tf.concat([t1, t2], 0)

<tf.Tensor: id=194, shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [85]:
# 将axis=1的维度拼接
tf.concat([t1, t2], 1)

<tf.Tensor: id=165, shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])>

#### <font id='split'>5.分割张量</font>

tf.split(value, num_or_size_spilits, axis=0)

- num_or_size_spilits
    - number: 切分成n个张量
    - list: [1,2,1] 表示切分成3个张量，长度分别是1，2，1

In [87]:
x = tf.range(24)
x = tf.reshape(x, [4, 6])
x 

<tf.Tensor: id=171, shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

In [88]:
tf.split(x, 2, 0)

[<tf.Tensor: id=174, shape=(2, 6), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])>,
 <tf.Tensor: id=175, shape=(2, 6), dtype=int32, numpy=
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])>]

In [89]:
tf.split(x, [1, 2, 1], 0)

[<tf.Tensor: id=178, shape=(1, 6), dtype=int32, numpy=array([[0, 1, 2, 3, 4, 5]])>,
 <tf.Tensor: id=179, shape=(2, 6), dtype=int32, numpy=
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])>,
 <tf.Tensor: id=180, shape=(1, 6), dtype=int32, numpy=array([[18, 19, 20, 21, 22, 23]])>]

#### <font id='stack'>6. 堆叠张量</font>

tf.stack(value, axis)

合并张量时，创建一个新的维度

In [91]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

In [92]:
tf.stack((x,y), axis=0)

<tf.Tensor: id=185, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [93]:
tf.stack((x,y), axis=1)

<tf.Tensor: id=186, shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

#### <font id='unstack'>7. 分解张量</font>

tf.unstack(value, axis)

分解张量时，减少一个维度

In [100]:
c = tf.constant([[1,2,3],[4,5,6]])
c

<tf.Tensor: id=196, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [101]:
tf.unstack(c, axis=0)

[<tf.Tensor: id=197, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: id=198, shape=(3,), dtype=int32, numpy=array([4, 5, 6])>]

In [102]:
tf.unstack(c, axis=1)

[<tf.Tensor: id=199, shape=(2,), dtype=int32, numpy=array([1, 4])>,
 <tf.Tensor: id=200, shape=(2,), dtype=int32, numpy=array([2, 5])>,
 <tf.Tensor: id=201, shape=(2,), dtype=int32, numpy=array([3, 6])>]